import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import StartPage from "../components/StartPage/StartPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Start Game.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <StartPage />
      </main>

    </div>
  )
}
